### ISSUE TITLE
Broken Image for Subtitle Extract

### ISSUE THREAD

**Issue by Middlepepper** [jellyfin/jellyfin-plugin-subtitleextract#11]
### Overview

When looking at the plugin in the _Catalog_ It will not show a Icon or the default icon in jellyfin

![image](https://user-images.githubusercontent.com/18419688/231628177-7834506d-76ed-471e-9e4d-9e730ae578e0.png)

### Steps to reproduce

1. Open Catalog
2. View Plugin

**Comment by GolDNenex** [comment]
https://github.com/jellyfin/jellyfin-ux/pull/55

**Comment by Middlepepper** [comment]
Thanks for the update GolDNenex, Looks like it all fixed.

**Comment by Middlepepper** [comment]
So with a little more work I found you can have the image bundled locally which should solve this issue.

1. adding a image.png to the repo that will automatically get detected.
2. Setting the image: "" value within the build.yaml

https://github.com/oddstr13/jellyfin-plugin-repository-manager/blob/master/Metadata.md

**Comment by crobibero** [comment]
I haven't gotten around to updating the repo... I'll put it on my list of things to do. This has been low priority since it doesn't really negatively impact anything.

**Comment by crobibero** [comment]
The repo server has been updated
