### ISSUE TITLE
Please provide more documentation

### ISSUE THREAD

**Issue by ulab** [jellyfin/jellyfin-plugin-subtitleextract#18]
As someone who is new to JF, it doesn't really help to read that a "Subtitle Extract" plugin "Extracts Subtitles" or to be more specific "Extracts embedded subtitles." :).

It would help if you explained why I'd want this, how it does it, etc. 

Does "extract" mean, the subtitles are moved out of the video container or just "copied" for example.

**Comment by crobibero** [comment]
When attempting playback with subtitles some clients need to fully extract the subtitles from the file before playback. This plugin leaves the file alone and just calls the Jellyfin function to store the subtitle streams as standalone files in the metadata directory.

**Comment by motoridersd** [comment]
Does it do it for EVERY library item? Can one select what libraries/shows/movies this applies to? Since the files are probably text, the space the metadata takes should be negligible but would be nice to see how much it takes. Where are the subtitles stored? What folder can we go to find/delete unwanted extracted subtitles?

**Comment by crobibero** [comment]
Yes, it does it for every item. Subtitles are exracted to whatever metadata directory Jellyfin is configured to use.

To clarify- all this plugin does is "pre-extract" the subtitle so playback can begin without waiting for extraction to complete.

**Comment by motoridersd** [comment]
Ok so it only will extract them when playing an item, and not for every item in the library that is unplayed. Will it delete the extracted subtitle after playback?

**Comment by crobibero** [comment]
No, it explicitly extracts the subtitle in a way that is unrelated to playback. This plugin does not delete any extracted subtitles.
