### ISSUE TITLE
Other subtitles types

### ISSUE THREAD

**Issue by Nodiink** [jellyfin/jellyfin-plugin-subtitleextract#20]
This plugin only support extraction of SRT and SSA/ASS sub types.
Why are other subs (vtt, idx, pgs, ...) excluded? Is there no benefit for Jellyfin to have these subtitles extracted?

**Comment by crobibero** [comment]
It's been a while since this was originally written, but I don't remember why I filtered by those formats.

I don't have the ability to test with the formats you mentioned, so someone else would have to create the PR with proof that it works

**Comment by thornbill** [comment]
I doubt image based formats like pgs would be possible?

**Comment by thornbill** [comment]
Oh doh right this just extracts them as is and doesn't convert to a different format. 🤦‍♂️ Just ignore me lol.

**Comment by crobibero** [comment]
This should be fixed in v4 of the plugin

**Comment by BlazeVertex** [comment]
> This should be fixed in v4 of the plugin

Formaat: S_TEXT/WEBVTT
Codec-ID: S_TEXT/WEBVTT

WebVTT subtitle files use the .vtt extension (sometimes shown as .wvtt inside containers).

As for this issue: I have it installed, but after completing the scan no subtitles were loaded.

Am I missing something?
