### ISSUE TITLE
Inclusion as default plugin for new installations of Jellyfin?

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/jellyfin-plugin-subtitleextract#22]
Hello! I ran into the slow subtitle loading issue today, and realized after half an hour of research that this was already fixed with this plugin. I was wondering if the plugin could be included by default in new Jellyfin installations as part of a proposal, as it is quite the bad experience for users if they fire up their content and the subtitles exhibit buggy behavior (slow loading, not loading at all, "Fetching additional data" spinning infinitely at the bottom right).

Or maybe this plugin can be recommended as part of the admin installation process ("you may want to install the subtitle extraction plugin to optimize your viewing experience"). Anything other than what I had to go through would be great for those just installing Jellyfin! Please let me know if this is a dumb idea and feel free to close the issue if so. :)

EDIT: reading over this I probably should clarify that I'm proposing for the plugin to be installed alongside Jellyfin for new installations. I'm already aware this is an official Jellyfin plugin included in the default repositories.

**Comment by crobibero** [comment]
What you are suggestion requires many server and web changes, some of which are planned. At this time there is no action that can be taken. 

Maybe the documentation would be a good place to start?
