### ISSUE TITLE
Subtitle extract only certain languages

### ISSUE THREAD

**Issue by David-Moreira** [jellyfin/jellyfin-plugin-subtitleextract#23]
Would it be possible to extract only for certain languages?

Thanks!

**Comment by crobibero** [comment]
Why would you want to only extract certain languages?
Additionally with 10.9 Jellyfin has been updated to extract all subtitles in one pass instead of a call per subtitle

**Comment by David-Moreira** [comment]
> Why would you want to only extract certain languages? Additionally with 10.9 Jellyfin has been updated to extract all subtitles in one pass instead of a call per subtitle

Precisely because what I have seen is it doing multiple passes per subtitle taking perhaps needlessly long time while someone might really only care about one or two subtitles.
Is the change you talk about live? I have recently seen this happen.

**Comment by crobibero** [comment]
10.9 is the next release of Jellyfin, so unless you are running a prerelease version the fix isn't in place.

**Comment by David-Moreira** [comment]
I see. It's a great fix/improvement then. 
Thank you!
