### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gVes** [jellyfin/jellyfin-plugin-subtitleextract#29]
Hi there

I’ve read a lot about this plugin, and frankly seems like exactly what I’m looking for. 
after installing the plugin I’ve restarted the server, and ran the plugin. 
Oddly it takes 2 seconds to complete. Afterwards I still can’t see any subtitles.
I’ve tried deleting and reinstalling the plugin a bunch of times. Not sure what I’ve done wrong or how to fix it, any ideas?

**Comment by crobibero** [comment]
All this plugin does is go through your library and pre-extract subtitles so Jellyfin clients can use them immediately instead of waiting for it to happen during playback. 

If you enable debug logging you should see the plugin testing each file
