### ISSUE TITLE
Seemlingly does nothing

### ISSUE THREAD

**Issue by platnub** [jellyfin/jellyfin-plugin-subtitleextract#31]
I've installed the plugin and it doesn't seem to do anything. A lot of media still has embed subtitles. I've had it installed for a few weeks now for any scheduled tasks to run, I've ran a few media scans. I've played media. It stays embed. What am I doing wrong?

Running 4.0.0
Jellyfin 10.9.3

**Comment by crobibero** [comment]
If all goes well you shouldn't notice anything except for subtitles being shown without delay. They will still be listed as embedded, but extracted to Jellyfin's metadata folders.
