### ISSUE TITLE
How to completely uninstall and delete generated files

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin-plugin-subtitleextract#38]
Sorry, I know it's not a bug, but I would like to completely uninstall this plugin and delete all generated files. Besides uninstalling the plugin via the web UI, which files/folders can I delete? Should I be concerned about deleting anything?

**Comment by crobibero** [comment]
You would need to remove the subtitle files which are in `your_data_directory/subtitles`
The files are extracted as Jellyfin metadata.

**Comment by nothing2obvi** [comment]
Thank you!
