### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by uSyzex** [jellyfin/jellyfin-plugin-subtitleextract#4]
Hi,

I would like to use this extension, but I don't have any clue on how it is supposed to behave within Jellyfin.
How to automatically extract subtitles when a new movie/serie is added ?
Does it need to be set up as a reccurent task ?

Regards,

**Comment by crobibero** [comment]
Yes, all you need to do is enable the scheduled task under server settings.

Thank you for reminding me to add docs

**Comment by uSyzex** [comment]
> Yes, all you need to do is enable the scheduled task under server settings.
> 
> Thank you for reminding me to add docs

Thank you for your answer, is there any way to trigger it when new media are added ?

**Comment by crobibero** [comment]
No, that is not currently possible

**Comment by uSyzex** [comment]
Okay thank very much for your help. Hope this will fix all my troubles with embbed sub.

**Comment by djayor** [comment]
Hi, did you already add to the documentation how this tool works?
Because after installation the only options that I have is disable and uninstall the plugin.
Looks like a good tool, I just still didn't understand how it works. Thanks
