### ISSUE TITLE
Store subtitles alongside file?

### ISSUE THREAD

**Issue by JRDevo** [jellyfin/jellyfin-plugin-subtitleextract#5]
Hello, thanks for the plugin, was really nice to see this in the plugin list!

If I'm not mistaken it seems subtitles are being stored in "Jellyfin\Server\data\subtitles", is it possible to store the subs alongside the media files with the same name?

Thanks!

**Comment by crobibero** [comment]
I undstand why you want this to happen but this plugin is very simple in that it just "pre-extracts" the subtitle so the server doesnt have to do it on the fly when attempting playback.
