### ISSUE TITLE
Reading just one subtitle at a time

### ISSUE THREAD

**Issue by bin-9100** [jellyfin/jellyfin-plugin-subtitleextract#6]
![Screenshot_2022-09-25-01-16-27-995_com android browser](https://user-images.githubusercontent.com/56068815/192110813-88e0f699-7980-4aa9-b92a-c22227c6fb7f.jpg)

Reading just one subtitle at a time is inefficient, and when a movie has more than one subtitle, it can take up to an hour.

**Comment by bin-9100** [comment]
I like this project very much. It's timely for me， 
ffmpeg seems to be able to extract more than one subtitle at a time

**Comment by alltilla** [comment]
As far as I can see the [`ISubtitleEncoder`](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/MediaEncoding/ISubtitleEncoder.cs) interface does not provide the API to extract multiple subtitles at once, so this cannot be fixed simply in this plugin.

**Comment by alltilla** [comment]
Opened a PR to jellyfin/jellyfin, let's see where this leads. :) https://github.com/jellyfin/jellyfin/pull/10884

**Comment by mirolm** [comment]
I opened similar issue [before](https://github.com/jellyfin/jellyfin/issues/3215) - jellyfin really trashes storage when you have anime shows with tons of fonts and subs. Calling ffmpeg while batching requests really could solve this.

**Comment by alltilla** [comment]
@mirolm My PR towards jellyfin implements the extraction of all subtitle streams in one go, so jellyfin only needs to read the source file once. If you agree with this approach, would you comment on the PR? Maybe it would get some traction.

jellyfin/jellyfin#10884

**Comment by alltilla** [comment]
Nice catch! I think I can do the same there. Let me look into it.

**Comment by mirolm** [comment]
Please do - i think dumping attachments causes more trouble than subs. Usually you can have 2-5 subs, but got 5-10-20-40 fonts embedded especially in anime shows.

**Comment by alltilla** [comment]
@mirolm Opened https://github.com/jellyfin/jellyfin/pull/11029 to bulk extract all attachments.

---

By the way, I think this issue is now fixed with https://github.com/jellyfin/jellyfin/pull/10884, maybe we should close it.

**Comment by memehammad** [comment]
Any workaround for this until 10.9 is released?

**Comment by crobibero** [comment]
> Any workaround for this until 10.9 is released?

No

**Comment by alltilla** [comment]
Yes, the jellyfin team has also found this problem. Make sure to apply this PR as well https://github.com/jellyfin/jellyfin/pull/10992

**Comment by alex9099** [comment]
Thanks! That seems to fix the issue.

In case anyone wants, here's the .deb (amd64) that i compiled with those two patches https://cloud.alexandrebadalo.pt/s/36Mq7xZf2WmxMsd

**Comment by crobibero** [comment]
Closing as complete
